### ISSUE TITLE
作者你好，很多文件都没有开放出来，比如一些整理的数据文件，可以开放一下你的

### ISSUE THREAD

**Issue by HongtaiZhang** [zw-SIMM/SFTLLMs_for_ChemText_Mining#3]
作者你好，你有很多数据没在github上上传啊，我想复现一下啊

**Comment by zw-SIMM** [comment]
Paragraph2Action的数据需要有pistachio许可证才提供，其它数据都上传了

**Comment by HongtaiZhang** [comment]
好的，但是在[Paragraph2RXNRole](https://github.com/zw-SIMM/SFTLLMs_for_ChemText_Mining/tree/main/Paragraph2RXNRole)中就没有这个Paragraph2RXNRole/Paragraph2Prod/evaluate_Paragraph2Prod.ipynb中打开的的表格文件results/predictions/prediction_of_saved_models-Mistral-7B-Instruct-v0.2-train_6163_lr5e-06_bs2-checkpoint-3082.csv，也是因为没有许可证吗

**Comment by zw-SIMM** [comment]
这个需要用微调后的模型推理测试集，再对预测的文件进行评估。

**Comment by HongtaiZhang** [comment]
好的谢谢你
